name: Vercel Production Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - main
jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        outputs:
            deployment-url: ${{ steps.preview.outputs.DEPLOYMENT_URL }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Send Notification 1
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Initiating Production Deployment! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    ${{ secrets.NTFY_URL }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21

            - name: Send Notification 2
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Node.js Installed! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    ${{ secrets.NTFY_URL }}

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: latest
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Send Notification 3
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "pnpm Installed! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    ${{ secrets.NTFY_URL }}

            - name: Install Vercel CLI
              run: pnpm add -g vercel@latest

            - name: Send Notification 4
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Vercel CLI Installed! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    ${{ secrets.NTFY_URL }}

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Send Notification 5
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Vercel Environment Information Pulled! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    ${{ secrets.NTFY_URL }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Send Notification 6
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Project Artifacts Built! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    ${{ secrets.NTFY_URL }}

            - name: Deploy Project Artifacts to Vercel
              id: preview
              run: |
                  vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
                  deploymentUrl=$(cat deployment-url.txt)
                  echo "Vercel Production URL: $deploymentUrl"
                  echo "DEPLOYMENT_URL=$deploymentUrl" >> $GITHUB_OUTPUT

            - name: Send Notification 7
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Project Artifacts Deployed to Vercel! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    ${{ secrets.NTFY_URL }}
    Ntfy-Success:
        needs: Deploy-Production
        runs-on: ubuntu-latest
        if: success()
        env:
            DEPLOYMENT_URL: ${{ needs.Deploy-Production.outputs.deployment-url }}
        steps:
            - name: Send Notification
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Your Portfolio is all set and live! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    -H "Actions: view, Open Site, $DEPLOYMENT_URL; view, Open Github, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
                    ${{ secrets.NTFY_URL }}
    Ntfy-Failure:
        needs: Deploy-Production
        runs-on: ubuntu-latest
        if: failure()
        steps:
            - name: Send Notification
              run: |
                  curl -u ${{ secrets.NTFY_CRED }} \
                    -d "Your Portfolio failed to build! 🚀💻" \
                    -H "Title: GitHub Baba" \
                    -H "Actions: view, Open Github, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
                    ${{ secrets.NTFY_URL }}
